name = "tally-discord-webhook"
main = "worker.js"
compatibility_date = "2025-08-19"

# Specifies which routes the Worker will run on
# You can also configure this from the Cloudflare dashboard
# routes = ["example.com/api/tally-webhook"]

# Environment variables (optional)
# [vars]
# ENVIRONMENT = "production"

# Specifies which zone the Worker will run in (optional)
# zone_id = "your-zone-id"

# KV namespaces (optional - can be used for form configurations in the future)
# [[kv_namespaces]]
# binding = "FORM_CONFIGS"
# id = "your-kv-namespace-id"

# Durable Objects (optional)
# [[durable_objects.bindings]]
# name = "FORM_COUNTER"
# class_name = "FormCounter"
